general:
  s3_regional_buckets: true
project:
  name: quickstart-aws-utility-meter-headend-system-simulator
  owner: michlitz@amazon.com
  shorten_stack_name: true
  regions:
    - us-east-1
    - us-east-2
    - us-west-2
  lambda_source_path: source/lambda
  lambda_zip_path: assets/lambda
  parameters:
    DeviceDataGeneratorInclude: 'Yes'
    TimestreamCreation: 'Create New'
    TimestreamTableName: 'readings'
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
tests:
  default:
    template: templates/headend.system.simulator.main.yaml
